# Link de ayuda: https://scikit-learn.org/stable/modules/naive_bayes.html

In [ ]:
#Carga librerias
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

import pandas as pd
import numpy as np

In [ ]:
# Cargar DataSet
X, y = load_iris(return_X_y=True)

In [ ]:
print("Shape X: ",X.shape)
print("Shape y: ",y.shape)

Shape X:  (150, 4)
Shape y:  (150,)


In [ ]:
# Split del DataSet
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.8, random_state=0)


In [ ]:
# Naive Bayes
gnb = GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)

In [ ]:
# Resultados

#print("Numbero de observaciones mal etiquetadas del total de %d observaciones : %d" %(X_test.shape[0], (y_test != y_pred).sum()))
print("Numero de datos en test:",X_test.shape[0])
print("Numero de aciertos:",metrics.accuracy_score(y_test,y_pred,normalize=False))
print("Numero de desaciertos:",(y_test != y_pred).sum())
print("Exactitud(Accuracy):",metrics.accuracy_score(y_test,y_pred))

# Matriz de Confución
print("\n\t---Matriz de Confución---")
print(metrics.confusion_matrix(y_test,y_pred))


Numero de datos en test: 120
Numero de aciertos: 112
Numero de desaciertos: 8
Exactitud(Accuracy): 0.9333333333333333

	---Matriz de Confución---
[[40  0  0]
 [ 0 39  0]
 [ 0  8 33]]
