In [3]:
# Importarcion librerias
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.svm import SVC

In [4]:
# Cargar dataSet CarEvaluation
dataSet = pd.read_csv('https://raw.githubusercontent.com/JohamSMC/electiva4/master/dataSets/dataSet-carEvaluation.txt', sep='\t', na_values=['?'])
dataSet

buying  maint  doors persons lug_boot safety  Class
0     vhigh  vhigh      2       2    small    low  unacc
1     vhigh  vhigh      2       2    small    med  unacc
2     vhigh  vhigh      2       2    small   high  unacc
3     vhigh  vhigh      2       2      med    low  unacc
4     vhigh  vhigh      2       2      med    med  unacc
...     ...    ...    ...     ...      ...    ...    ...
1723    low    low  5more    more      med    med   good
1724    low    low  5more    more      med   high  vgood
1725    low    low  5more    more      big    low  unacc
1726    low    low  5more    more      big    med   good
1727    low    low  5more    more      big   high  vgood

[1728 rows x 7 columns]

In [5]:
# Información DataSet
dataSet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   buying    1728 non-null   object
 1   maint     1728 non-null   object
 2   doors     1728 non-null   object
 3   persons   1728 non-null   object
 4   lug_boot  1728 non-null   object
 5   safety    1728 non-null   object
 6   Class     1728 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB


## ***Limpieza de datos***

In [6]:
print("Numero Filas y Columnas dataSet = ",dataSet.shape)
# Valores nulos en dataSet application
print("Valores nulos en dataSet credit:\n")
print(dataSet.isnull().sum())

Numero Filas y Columnas dataSet =  (1728, 7)
Valores nulos en dataSet credit:

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
Class       0
dtype: int64


In [7]:
# Valores del atributo doors
dataSet.doors.value_counts()

4        432
3        432
5more    432
2        432
Name: doors, dtype: int64

In [8]:
# Cambio tipo de variablde DOORS a string
dataSet.doors = dataSet.doors.astype(str)
# Cambia todo los "doors" de valor "5more" a 5
dataSet.doors = dataSet.doors.replace({'5more':5})
# Valores del atributo doors
dataSet.doors.value_counts()

4    432
3    432
2    432
5    432
Name: doors, dtype: int64

In [9]:
# Valores del atributo persons
dataSet.persons.value_counts()

4       576
more    576
2       576
Name: persons, dtype: int64

In [10]:
# Cambio tipo de variablde PERSONS a string
dataSet.persons = dataSet.persons.astype(str)
# Cambia todo los "doors" de valor "more" a 5
dataSet.persons = dataSet.persons.replace({'more':5})
# Valores del atributo persons
dataSet.persons.value_counts()

4    576
2    576
5    576
Name: persons, dtype: int64

### ***Cambiar atributos de Cualitativos Nominales A Cuantitativos Discretos***

In [11]:
# Valores de buying
dataSet.buying.value_counts()

low      432
med      432
high     432
vhigh    432
Name: buying, dtype: int64

In [12]:
# Reemplazar los valores
dictionary_replacement = {'low':1,
                          'med':2,
                          'high':3,
                          'vhigh':4}
dataSet.buying = dataSet.buying.map(dictionary_replacement)
# Valores de buying
dataSet.buying.value_counts()

4    432
3    432
2    432
1    432
Name: buying, dtype: int64

In [13]:
# Valores de maint
dataSet.maint.value_counts()

low      432
med      432
high     432
vhigh    432
Name: maint, dtype: int64

In [14]:
# Reemplazar los valores
dictionary_replacement = {'low':1,
                          'med':2,
                          'high':3,
                          'vhigh':4}
dataSet.maint = dataSet.maint.map(dictionary_replacement)
# Valores de buying
dataSet.maint.value_counts()

4    432
3    432
2    432
1    432
Name: maint, dtype: int64

In [15]:
# Valores de lug_boot
dataSet.lug_boot.value_counts()

med      576
big      576
small    576
Name: lug_boot, dtype: int64

In [16]:
# Reemplazar los valores
dictionary_replacement = {'small':1,
                          'med':2,
                          'big':3}
dataSet.lug_boot = dataSet.lug_boot.map(dictionary_replacement)
# Valores de buying
dataSet.lug_boot.value_counts()

3    576
2    576
1    576
Name: lug_boot, dtype: int64

In [17]:
# Valores de safety
dataSet.safety.value_counts()

low     576
med     576
high    576
Name: safety, dtype: int64

In [18]:
# Reemplazar los valores
dictionary_replacement = {'low':1,
                          'med':2,
                          'high':3}
dataSet.safety = dataSet.safety.map(dictionary_replacement)
# Valores de buying
dataSet.safety.value_counts()

3    576
2    576
1    576
Name: safety, dtype: int64

In [19]:
dataSet.head(n=5)

buying  maint doors persons  lug_boot  safety  Class
0       4      4     2       2         1       1  unacc
1       4      4     2       2         1       2  unacc
2       4      4     2       2         1       3  unacc
3       4      4     2       2         2       1  unacc
4       4      4     2       2         2       2  unacc

In [20]:
# Valores de la atributo "Class"
dataSet.Class.value_counts()

unacc    1210
acc       384
good       69
vgood      65
Name: Class, dtype: int64

## ***Splitting Data***

In [21]:
# Definir semilla y tamaño del conjuto de prueba
seed =123
test_size=0.2

In [22]:
# Se separa el atributo objetivo(target) en "y" y los demas atributos en "X"
X = dataSet.drop(['Class'],axis=1)
y = dataSet['Class']

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = test_size, random_state = seed)

## ***Máquinas de vectores de soporte***

In [24]:
from sklearn.svm import SVC

In [25]:
clf = SVC(kernel='rbf')
#clf = SVC(kernel='linear')
#clf = SVC(kernel='poly')
#clf = SVC(kernel='sigmoid')
clf.fit(X_train, y_train)

# Predecir la respuesta para el conjunto de datos de prueba
y_pred = clf.predict(X_test)

In [26]:
# Resultados

print("Numero de datos en test:",X_test.shape[0])
print("Numero de aciertos:",metrics.accuracy_score(y_test,y_pred,normalize=False))
print("Numero de desaciertos:",(y_test != y_pred).sum())
print("Exactitud(Accuracy):",metrics.accuracy_score(y_test,y_pred))

# Matriz de Confución
print("\n\t---Matriz de Confución SVM---")
print(metrics.confusion_matrix(y_test,y_pred))

Numero de datos en test: 346
Numero de aciertos: 328
Numero de desaciertos: 18
Exactitud(Accuracy): 0.9479768786127167

	---Matriz de Confución SVM---
[[ 80   0   4   0]
 [  2   9   0   2]
 [  9   0 228   0]
 [  1   0   0  11]]


## **Validacion Cruzada**

In [27]:
# Importarcion librerias
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

***KF***

In [35]:
print("Accuracy with Splitting:",metrics.accuracy_score(y_test,y_pred),"\n")

for iteratorKF in range(5,11):
  kf = KFold(n_splits=iteratorKF,shuffle=True,random_state=seed)
  scores_cross = cross_val_score(clf, X, y, cv = kf)
  #Scores
  print("KF = ",kf.n_splits)  
  print("Accuracies with Cross Validation KF: ", scores_cross)
  print("Accuracy mean with Cross Validation KF: ", scores_cross.mean())
  print("\n")


Accuracy with Splitting: 0.9479768786127167 

KF =  5
Accuracies with Cross Validation KF:  [0.94797688 0.96820809 0.93930636 0.93913043 0.95362319]
Accuracy mean with Cross Validation KF:  0.9496489905336348


KF =  6
Accuracies with Cross Validation KF:  [0.94444444 0.96180556 0.94444444 0.94444444 0.92361111 0.96527778]
Accuracy mean with Cross Validation KF:  0.9473379629629629


KF =  7
Accuracies with Cross Validation KF:  [0.94736842 0.95951417 0.94331984 0.94331984 0.95951417 0.91497976
 0.96341463]
Accuracy mean with Cross Validation KF:  0.9473472612111894


KF =  8
Accuracies with Cross Validation KF:  [0.94444444 0.95833333 0.97222222 0.93981481 0.94444444 0.95833333
 0.90740741 0.96759259]
Accuracy mean with Cross Validation KF:  0.9490740740740741


KF =  9
Accuracies with Cross Validation KF:  [0.953125   0.953125   0.97395833 0.953125   0.94270833 0.95833333
 0.9375     0.94270833 0.97395833]
Accuracy mean with Cross Validation KF:  0.9542824074074076


KF =  10
Accurac

### ***SKF***

In [37]:
print("Accuracy with Splitting:",metrics.accuracy_score(y_test,y_pred),"\n")

for iteratorSKF in range(5,11):
  skf = StratifiedKFold(n_splits=iteratorSKF,shuffle=True,random_state=seed)
  scores_cross = cross_val_score(clf, X, y, cv = skf)
  #Scores
  print("KF = ",skf.n_splits)  
  print("Accuracies with Cross Validation SKF: ", scores_cross)
  print("Accuracy mean with Cross Validation SKF: ", scores_cross.mean())
  print("\n")


Accuracy with Splitting: 0.9479768786127167 

KF =  5
Accuracies with Cross Validation SKF:  [0.9566474  0.96531792 0.94219653 0.95652174 0.94202899]
Accuracy mean with Cross Validation SKF:  0.9525425148697326


KF =  6
Accuracies with Cross Validation SKF:  [0.96875    0.95833333 0.93402778 0.95138889 0.96527778 0.94444444]
Accuracy mean with Cross Validation SKF:  0.9537037037037037


KF =  7
Accuracies with Cross Validation SKF:  [0.96356275 0.94736842 0.94331984 0.95546559 0.951417   0.94331984
 0.94308943]
Accuracy mean with Cross Validation SKF:  0.9496489817414079


KF =  8
Accuracies with Cross Validation SKF:  [0.96759259 0.94444444 0.9537037  0.94907407 0.9537037  0.9537037
 0.93518519 0.94907407]
Accuracy mean with Cross Validation SKF:  0.9508101851851852


KF =  9
Accuracies with Cross Validation SKF:  [0.96875    0.9375     0.97395833 0.953125   0.94791667 0.953125
 0.953125   0.92708333 0.94791667]
Accuracy mean with Cross Validation SKF:  0.9513888888888888


KF =  10
